# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "{{ cookiecutter.box }}"
  config.env.enable # Enable vagrant-env plugin

  config.vm.provider 'virtualbox' do |vb|
    vb.name = "{{ cookiecutter.vb_name }}"
  end

  ANSIBLE_ARGS = ENV["ANSIBLE_ARGS"]
  PLAYBOOK = ENV["PLAYBOOK"] || "/etc/ansible/playbook.yml"

  config.vm.synced_folder "ansible", "/etc/ansible/", type: "rsync"

  config.vm.provision "shell", inline: "dpkg -s ansible > /dev/null 2>&1 \
    || { apt-get remove -y python2; apt-get autoremove; apt-get install -y ansible; }"
  config.vm.provision "shell", inline: "
    sudo ansible-playbook \
        --verbose \
        --inventory 'vagrant,' \
        --connection=local \
        #{ANSIBLE_ARGS} \
        #{PLAYBOOK}"
end
