# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "{{ cookiecutter.box }}"
  config.env.enable # Enable vagrant-env plugin

  config.vm.provider 'virtualbox' do |vb|
    vb.name = "{{ cookiecutter.vb_name }}"
  end
end
